Fix: Improve handling of query parameters in API module
dewald-els/omedacity-js pull request #4
Opened 2024-01-27 04:46 UTC by bslie

This commit refactors the `createQueryParams` function in the `src/api/index.ts` file to better handle query parameters. The updated code adds a helper function `addParam` that handles the different types of parameter values. It properly handles cases where the parameter is `false`, an array, or an object. The function converts the values to their corresponding query string format and removes any parameters with empty values. The refactored code improves maintainability and readability.

Changes:
- Refactored the `createQueryParams` function to use a helper function `addParam`
- Improved handling of different types of parameter values
- Removed unnecessary checks and duplicated code
- Updated the code to use `Object.entries` and `Array.isArray` for better clarity and consistency

2024-01-27 04:51 UTC, bslie commented
```bush
Test Suites:  6 passed, 6 total
Tests:        18 passed, 18 total
✨ Done in 1.90s.
```

2024-01-29 06:06 UTC, dewald-els commented on .github/workflows/publish.yml
This file should not be deleted as it is used to deploy to npm :)

2024-01-29 06:06 UTC, dewald-els commented on .github/workflows/node.js.yml
This is already handled in the publish.yml file

2024-01-29 06:07 UTC, dewald-els commented on .gitignore
You should commit your lock file since this is a top level repo :) It will ensure stability until we manually update dependency versions

2024-01-29 06:09 UTC, dewald-els requested changes
Just some changes, specifically: 
- Don't delete the publish.yml, it's used to build, test and deploy to npm
- The node.js.yml is unnecessary since testing, building and deploying is already handled in the publish.yml
- You shouldn't ignore your lock file

2024-01-29 06:11 UTC, dewald-els commented
@bslie Nice work! Thanks for this, could you also bump the version 0.6.4 in the package.json and the api/index.ts file? :) This will ensure a deploy to npm. I still have to set up semantic versioning, just haven't had the time

2024-01-29 06:11 UTC, bslie commented on .github/workflows/node.js.yml
I apologize, I'm not very familiar with GitHub, I made a Pull Request and then I deleted it, but the changes were synchronized

2024-01-29 06:17 UTC, dewald-els commented on .github/workflows/node.js.yml
No problem, don't worry about it :)

2024-01-29 14:45 UTC, dewald-els approved these changes
lgtm 👍

2024-01-29 15:07 UTC, merged